### ISSUE TITLE
`watchConversations` hook is not triggered when removing a message

### ISSUE THREAD

**Issue by HenriChabert** [nabla/nabla-react-native#4]
Hello team,
It seems that `watcher` returned by `watchConversations` is not triggered when we delete a message from a conversation. Is it a known behaviour? Is it linked to the recent addition of `content_deleted` webhook?
Thanks!

**Comment by benoitletondor** [comment]
Hey, thanks for your question.

Yes this is normal behavior. If you are using `watchConversation` (a single one, not all) then you'll be notified if a message is deleted in that conversation, but the watcher for all conversations isn't triggered on all internal conversation event.

If you're interested in watching that, watching the conversation itself is the way to go.
